name: CD Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add overall job timeout
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.P_KEY }}" > ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/deploy_key
          chmod 600 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/deploy_key -v root@64.227.156.33 "echo 'SSH connection test successful'"

      - name: Deploy with SSH
        run: |
          # Using -t to force pseudo-terminal allocation
          ssh -i ~/.ssh/deploy_key -t root@64.227.156.33 "
            set -e
            echo 'Starting deployment...'
            
            echo 'Checking Node.js installation...'
            if ! command -v node &> /dev/null; then
              echo 'Installing Node.js...'
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt-get install -y nodejs
            fi

            echo 'Checking pnpm installation...'
            if ! command -v pnpm &> /dev/null; then
              echo 'Installing pnpm...'
              npm install -g pnpm
            fi

            echo 'Checking PM2 installation...'
            if ! command -v pm2 &> /dev/null; then
              echo 'Installing PM2...'
              npm install -g pm2
            fi
            
            echo 'Navigating to project directory...'
            cd devops-cicd
            
            echo 'Pulling latest changes...'
            git pull
            
            echo 'Cleaning up old processes and cache...'
            pkill -f 'next build' || true
            rm -rf .next
            rm -rf node_modules/.cache
            
            echo 'Installing dependencies...'
            timeout 5m pnpm install
            
            echo 'Building application...'
            timeout 5m pnpm run build
            
            echo 'Restarting PM2 processes...'
            pm2 delete all || true
            pm2 start npm --name 'next-app' -- start
            
            echo 'Deployment completed successfully!'
          "
