name: CD Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.P_KEY }}" > ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/deploy_key
          chmod 600 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key

      - name: Deploy with SSH
        run: |
          ssh -i ~/.ssh/deploy_key root@64.227.156.33 "
            # Install Node.js and npm if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt-get install -y nodejs
            fi

            # Install pnpm globally
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi

            # Install PM2 globally
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            cd devops-cicd && 
            git pull && 
            pnpm install && 
            pnpm run build && 
            pm2 restart all
          "
