name: CD Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.P_KEY }}" > ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/deploy_key
          chmod 600 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key

      - name: Deploy with SSH
        run: |
          ssh -i ~/.ssh/deploy_key root@64.227.156.33 "
            # Install pnpm if not installed
            if ! command -v pnpm &> /dev/null; then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
            fi
            
            # Set up pnpm in current session
            export PNPM_HOME="/root/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"
            
            # Verify pnpm is accessible
            $PNPM_HOME/pnpm --version
            
            cd devops-cicd && 
            git pull && 
            $PNPM_HOME/pnpm install && 
            $PNPM_HOME/pnpm run build && 
            pm2 restart all
          "
