name: CD Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.P_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H 64.227.156.33 >> ~/.ssh/known_hosts
          
      - name: Deploy with SSH
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@64.227.156.33 "cd devops-cicd && git pull && pnpm install && pnpm run build && pm2 restart all"
