name: CD Prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Add overall job timeout
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.P_KEY }}" > ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/deploy_key
          chmod 600 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key

      - name: Deploy with SSH
        run: |
          ssh -i ~/.ssh/deploy_key root@64.227.156.33 "
            # Install Node.js and npm if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt-get install -y nodejs
            fi

            # Install pnpm globally
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi

            # Install PM2 globally
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            cd devops-cicd && 
            git pull && 
            
            # Kill any hanging build processes
            pkill -f 'next build' || true
            
            # Clean build cache and node_modules
            rm -rf .next
            rm -rf node_modules/.cache
            
            # Install dependencies and build with a timeout
            timeout 5m pnpm install &&
            timeout 5m pnpm run build &&
            
            # Restart the application with PM2
            pm2 delete all || true
            pm2 start npm --name 'next-app' -- start
          "
